### ISSUE TITLE
List object as no attribute 'join'

### ISSUE THREAD

**Issue by ArthurBacci64** [lagmoellertim/unsilence#11] opened 2020-06-25 01:02 UTC
![captura](https://user-images.githubusercontent.com/59983362/85641815-13016780-b666-11ea-8d42-784705c95a54.png)
I installed with `pip3 install unsilence`, and tried with `pip install unsilence` after `pip3 uninstall unsilence`.

Maybe a `[0,1].join("")` instead of `"".join([0,1])`?

**Comment by lagmoellertim** [comment] 2020-06-25 14:21
I cannot replicate the issue. Unsilence only works with python >3.7 and I would recommend you to use pipx for installation to avoid other problems (manual is in the readme)

**Comment by lagmoellertim** [comment] 2020-07-07 19:43
Hey, I'm sorry I haven't answered till now, I'm really short on time and probably am not able to look any further into your Issue until next month, sorry!

**Comment by ilyakharlamov** [comment] 2020-07-11 20:29
@ArthurBacci64 You need to install ffmpeg 4.3.2 to avoid the error

**Comment by lagmoellertim** [comment] 2020-07-18 22:45
This should be fixed by the new release, feel free to re-open this issue if the issue is still present.

**Closed by lagmoellertim** 2020-07-18 22:45 UTC
